# Generated by Django 5.1 on 2025-12-19 01:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('issue_no', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='契約NO')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='契約日')),
                ('site', models.CharField(max_length=200, verbose_name='現場名')),
                ('site_address', models.CharField(max_length=255, verbose_name='現場住所')),
                ('customer', models.CharField(max_length=200, verbose_name='得意先')),
                ('contractor', models.CharField(max_length=200, verbose_name='施工者名')),
                ('contact', models.CharField(max_length=100, verbose_name='連絡先')),
                ('product', models.CharField(max_length=100, verbose_name='商品名')),
                ('product_category', models.CharField(max_length=100, verbose_name='商品区分')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('firstship_date', models.DateField(verbose_name='初回出荷予定日')),
                ('qty', models.FloatField(verbose_name='契約数量')),
                ('rotation', models.IntegerField(verbose_name='予定回転数')),
                ('price', models.IntegerField(verbose_name='販売単価')),
                ('test', models.BooleanField(default=False, verbose_name='現場試験')),
                ('night', models.BooleanField(default=False, verbose_name='夜間')),
                ('outside23', models.BooleanField(default=False, verbose_name='23区外')),
                ('material_delivery', models.BooleanField(default=False, verbose_name='材料渡し')),
                ('specialnote', models.TextField(blank=True, verbose_name='特記項目')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_date', models.DateField(default=django.utils.timezone.now, verbose_name='出荷日')),
                ('ship_time', models.TimeField(verbose_name='出荷時間')),
                ('ship_qty', models.FloatField(verbose_name='出荷量')),
                ('car_no', models.CharField(max_length=50, verbose_name='車両番号')),
                ('total_unit', models.IntegerField(verbose_name='累計台数')),
                ('total_ship_qty', models.FloatField(verbose_name='累計出荷量')),
                ('before_car_no', models.CharField(blank=True, max_length=50, verbose_name='前車NO')),
                ('material_soil', models.CharField(blank=True, max_length=100, verbose_name='原料土')),
                ('water', models.FloatField(default=0, verbose_name='水')),
                ('cementBB', models.FloatField(default=0, verbose_name='セメントBB')),
                ('recycle_sand', models.FloatField(default=0, verbose_name='再生砂')),
                ('admixture', models.FloatField(default=0, verbose_name='混和剤')),
                ('material_soil_wm', models.FloatField(default=0, verbose_name='原料土wm')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='受注紐付')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='担当者名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.staff', verbose_name='担当者名'),
        ),
    ]
