# Generated by Django 5.1 on 2026-01-07 00:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(default='', max_length=10, verbose_name='契約NO')),
                ('ship_date', models.DateField(default=django.utils.timezone.now, verbose_name='出荷日')),
                ('ship_time', models.TimeField(default=django.utils.timezone.now, verbose_name='出荷時間')),
                ('ship_qty', models.FloatField(default=6.0, verbose_name='出荷量')),
                ('car_no', models.CharField(default='', max_length=3, verbose_name='車両番号')),
                ('total_unit', models.IntegerField(default=0, verbose_name='累計台数')),
                ('total_ship_qty', models.FloatField(default=0.0, verbose_name='累計出荷量')),
                ('before_car_no', models.CharField(blank=True, default='', max_length=3, verbose_name='前車NO')),
                ('contract_qty', models.FloatField(default=0, verbose_name='契約数量')),
                ('remaining_qty', models.FloatField(default=0, verbose_name='残量')),
                ('site', models.CharField(default='', max_length=100, verbose_name='現場名')),
                ('site_address', models.CharField(blank=True, default='', max_length=200, verbose_name='現場住所')),
                ('customer', models.CharField(default='', max_length=100, verbose_name='得意先')),
                ('contractor', models.CharField(blank=True, default='', max_length=100, verbose_name='施工者名')),
                ('coordinator', models.CharField(blank=True, default='', max_length=50, verbose_name='担当者名')),
                ('contact', models.CharField(blank=True, default='', max_length=50, verbose_name='連絡先')),
                ('product', models.CharField(default='', max_length=100, verbose_name='商品名')),
                ('product_category', models.CharField(blank=True, default='', max_length=100, verbose_name='標準/規格')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('specialnote', models.TextField(blank=True, default='', verbose_name='特記事項')),
                ('rotation', models.FloatField(blank=True, default=0, null=True, verbose_name='予定回転数')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='販売単価')),
                ('material_soil', models.FloatField(blank=True, default=0, null=True, verbose_name='原料土')),
                ('water', models.FloatField(blank=True, default=0, null=True, verbose_name='水')),
                ('cementBB', models.FloatField(blank=True, default=0, null=True, verbose_name='セメントBB')),
                ('recycle_sand', models.FloatField(blank=True, default=0, null=True, verbose_name='再生砂')),
                ('admixture', models.FloatField(blank=True, default=0, null=True, verbose_name='混和剤')),
                ('material_soil_wm', models.FloatField(blank=True, default=0, null=True, verbose_name='原料土wm')),
                ('test', models.BooleanField(default=False, verbose_name='現場試験')),
                ('night', models.BooleanField(default=False, verbose_name='夜間')),
                ('outside23', models.BooleanField(default=False, verbose_name='23区外')),
                ('material_delivery', models.BooleanField(default=False, verbose_name='材料渡し')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_timeout_minutes', models.IntegerField(default=30, verbose_name='セッション有効期限(分)')),
            ],
            options={
                'verbose_name': 'システム設定',
            },
        ),
        migrations.CreateModel(
            name='UnitPriceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='区分')),
                ('item_name', models.CharField(max_length=100, verbose_name='項目名')),
                ('partition_price', models.IntegerField(verbose_name='仕切り価格')),
                ('standard_price', models.IntegerField(default=0, verbose_name='標準販売価格')),
            ],
            options={
                'verbose_name': '単価マスタ',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin_user', models.BooleanField(default=False, verbose_name='管理者権限')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='表示名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('issue_no', models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, verbose_name='契約NO')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='契約日')),
                ('site', models.CharField(max_length=200, verbose_name='現場名')),
                ('site_address', models.CharField(max_length=255, verbose_name='現場住所')),
                ('customer', models.CharField(max_length=200, verbose_name='得意先')),
                ('contractor', models.CharField(max_length=200, verbose_name='施工者名')),
                ('contact', models.CharField(max_length=100, verbose_name='連絡先')),
                ('product', models.CharField(max_length=100, verbose_name='商品名')),
                ('product_category', models.CharField(max_length=100, verbose_name='商品区分')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('firstship_date', models.DateField(verbose_name='初回出荷予定日')),
                ('qty', models.FloatField(verbose_name='契約数量')),
                ('rotation', models.IntegerField(verbose_name='予定回転数')),
                ('price', models.IntegerField(verbose_name='販売単価')),
                ('material_soil', models.CharField(blank=True, max_length=100, verbose_name='原料土')),
                ('water', models.FloatField(default=0, verbose_name='水')),
                ('cementBB', models.FloatField(default=0, verbose_name='セメントBB')),
                ('recycle_sand', models.FloatField(default=0, verbose_name='再生砂')),
                ('admixture', models.FloatField(default=0, verbose_name='混和剤')),
                ('material_soil_wm', models.FloatField(default=0, verbose_name='原料土wm')),
                ('test', models.BooleanField(default=False, verbose_name='現場試験')),
                ('night', models.BooleanField(default=False, verbose_name='夜間')),
                ('outside23', models.BooleanField(default=False, verbose_name='23区外')),
                ('material_delivery', models.BooleanField(default=False, verbose_name='材料渡し')),
                ('specialnote', models.TextField(blank=True, verbose_name='特記項目')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.staff', verbose_name='担当者名')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('section', models.CharField(max_length=10)),
                ('row_index', models.IntegerField()),
                ('site_name', models.CharField(blank=True, max_length=200)),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('plan_qty', models.FloatField(blank=True, null=True)),
                ('truck_count', models.IntegerField(blank=True, null=True)),
                ('plan_note', models.TextField(blank=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'unique_together': {('plan_date', 'section', 'row_index')},
            },
        ),
    ]
