# Generated by Django 5.1 on 2025-12-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admixture',
            field=models.FloatField(default=0, verbose_name='混和剤'),
        ),
        migrations.AddField(
            model_name='order',
            name='cementBB',
            field=models.FloatField(default=0, verbose_name='セメントBB'),
        ),
        migrations.AddField(
            model_name='order',
            name='material_soil',
            field=models.CharField(blank=True, max_length=100, verbose_name='原料土'),
        ),
        migrations.AddField(
            model_name='order',
            name='material_soil_wm',
            field=models.FloatField(default=0, verbose_name='原料土wm'),
        ),
        migrations.AddField(
            model_name='order',
            name='recycle_sand',
            field=models.FloatField(default=0, verbose_name='再生砂'),
        ),
        migrations.AddField(
            model_name='order',
            name='water',
            field=models.FloatField(default=0, verbose_name='水'),
        ),
    ]
