# Generated by Django 5.1 on 2025-12-25 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='order',
        ),
        migrations.AddField(
            model_name='shipment',
            name='admixture',
            field=models.FloatField(default=0, verbose_name='混和剤'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cementBB',
            field=models.FloatField(default=0, verbose_name='セメントBB'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='連絡先'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='contractor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='施工者名'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='coordinator',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='担当者名'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.CharField(default='', max_length=100, verbose_name='得意先'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='issue_no',
            field=models.CharField(default='', max_length=10, verbose_name='契約NO'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='material_delivery',
            field=models.BooleanField(default=False, verbose_name='材料渡し'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='material_soil',
            field=models.FloatField(default=0, verbose_name='原料土'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='material_soil_wm',
            field=models.FloatField(default=0, verbose_name='原料土wm'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='night',
            field=models.BooleanField(default=False, verbose_name='夜間'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='outside23',
            field=models.BooleanField(default=False, verbose_name='23区外'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(default=0, verbose_name='販売単価'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.CharField(default='', max_length=100, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='標準/規格'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='recycle_sand',
            field=models.FloatField(default=0, verbose_name='再生砂'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rotation',
            field=models.FloatField(default=0, verbose_name='予定回転数'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='site',
            field=models.CharField(default='', max_length=100, verbose_name='現場名'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='site_address',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='現場住所'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='specialnote',
            field=models.TextField(blank=True, default='', verbose_name='特記事項'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='test',
            field=models.BooleanField(default=False, verbose_name='現場試験'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='water',
            field=models.FloatField(default=0, verbose_name='水'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='before_car_no',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='前車NO'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='car_no',
            field=models.CharField(default='', max_length=3, verbose_name='車両番号'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_qty',
            field=models.FloatField(default=6.0, verbose_name='出荷量'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ship_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='出荷時間'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_ship_qty',
            field=models.FloatField(default=0.0, verbose_name='累計出荷量'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='total_unit',
            field=models.IntegerField(default=0, verbose_name='累計台数'),
        ),
    ]
