# Generated by Django 5.1 on 2025-12-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_admixture_order_cementbb_order_material_soil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='admixture',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='cementBB',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='material_soil',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='material_soil_wm',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='recycle_sand',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='water',
        ),
    ]
