# Generated by Django 5.1 on 2025-12-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_shipment_order_shipment_admixture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='contract_qty',
            field=models.FloatField(default=0.0, verbose_name='契約数量'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='remaining_qty',
            field=models.FloatField(default=0.0, verbose_name='残量'),
        ),
    ]
