# Generated by Django 5.1 on 2025-12-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shipment_contract_qty_shipment_remaining_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='admixture',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='混和剤'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cementBB',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='セメントBB'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='material_soil',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='原料土'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='material_soil_wm',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='原料土wm'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='販売単価'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recycle_sand',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='再生砂'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='rotation',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='予定回転数'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='water',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='水'),
        ),
    ]
