# Generated by Django 5.1 on 2025-12-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_shipment_admixture_remove_shipment_cementbb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issue_no',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, verbose_name='契約NO'),
        ),
    ]
